using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("1.3.2.0")]
[assembly: AssemblyTitleAttribute("RVGbilling")]
[assembly: AssemblyDescriptionAttribute("Billing system (C# + NHibernate + PostgreSQL) by Kotov Vadim, Tihonov Roman and G" +
    "alina Ponomareva.")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2008-2009, RVG, Inc.")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("RVG")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyProductAttribute("RVGbilling")]

